#!/usr/bin/env php
<?php

use App\Commands\MigrateCommand;
use Symfony\Component\Console\Application;

require __DIR__ . '/vendor/autoload.php';

$application = new Application();

$application->add(new MigrateCommand);

try {
    $application->run();
} catch (Exception $e) {
    dd($e);
}